version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: "docker:latest"
    working_directory: ~/project
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: docker build .
      - run: docker system prune --force

  deploy:
    docker:
      - image: "cimg/base:2023.07"
    steps:
      - checkout
      - heroku/install
      - run: heroku container:login
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web

workflows:
  test_my_app:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
