version: 2.1

jobs:
  build:
    docker:
      - image: "docker:latest"
    working_directory: ~/project
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: docker build .
      - run: docker system prune --force

  deploy:
    docker:
      - image: "cimg/base:2023.07"
    steps:
      - checkout
      - run: >
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/kaden-backend.git
          main

workflows:
  test_my_app:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
