version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: "docker:latest"
    working_directory: ~/project
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: docker build .
      - run: docker system prune --force

  test:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - run: npm test

  deploy:
    docker:
      - image: "cimg/base:2023.07"
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - heroku/install
      - run: heroku container:login
      - run: heroku container:push -a kaden-backend web
      - run: heroku container:release -a kaden-backend web

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: main
