export const AVATAR_SRC =
  "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500";
export const dummyPostData = [
  {
    id: "bd7acbea-c1b1-46c2-aed5-3ad53abb28ba",
    active: true,
    fullName: "Aafreen Khan",
    author: {
      first: "Steve",
      last: "Jobs",
      username: "Steven Penava",
    },
    track: {
      title: "Test Track Title",
      artist: "Test Artist",
      albumTitle: "Test Album Title",
      spotifyImageUrl: AVATAR_SRC,
      appleMusicImageUrl: AVATAR_SRC,
    },
  },
  {
    id: "3ac68afc-c605-48d3-a4f8-fbd91aa97f63",
    active: true,
    fullName: "Aafreen Khan",
    author: {
      first: "Steve",
      last: "Jobs",
      username: "ettep",
    },
    track: {
      title: "Test Track Title",
      artist: "Test Artist",
      albumTitle: "Test Album Title",
      spotifyImageUrl: AVATAR_SRC,
      appleMusicImageUrl: AVATAR_SRC,
    },
  },
  {
    id: "58694a0f-3da1-471f-bd96-145571e29d72",
    active: true,
    fullName: "Aafreen Khan",
    author: {
      first: "Steve",
      last: "Jobs",
      username: "ettep",
    },
    track: {
      title: "Test Track Title",
      artist: "Test Artist",
      albumTitle: "Test Album Title",
      spotifyImageUrl: AVATAR_SRC,
      appleMusicImageUrl: AVATAR_SRC,
    },
  },
  {
    id: "68694a0f-3da1-431f-bd56-142371e29d72",
    active: true,
    fullName: "Aafreen Khan",
    author: {
      first: "Steve",
      last: "Jobs",
      username: "ettep",
    },
    track: {
      title: "Test Track Title",
      artist: "Test Artist",
      albumTitle: "Test Album Title",
      spotifyImageUrl: AVATAR_SRC,
      appleMusicImageUrl: AVATAR_SRC,
    },
  },
  {
    id: "28694a0f-3da1-471f-bd96-142456e29d72",
    active: true,
    fullName: "Aafreen Khan",
    author: {
      first: "Steve",
      last: "Jobs",
      username: "ettep",
    },
    track: {
      title: "Test Track Title",
      artist: "Test Artist",
      albumTitle: "Test Album Title",
      spotifyImageUrl: AVATAR_SRC,
      appleMusicImageUrl: AVATAR_SRC,
    },
  },
  {
    id: "28694a0f-3da1-451f-bd96-142456e29d72",
    active: true,
    fullName: "Aafreen Khan",
    author: {
      first: "Steve",
      last: "Jobs",
      username: "ettep",
    },
    track: {
      title: "Test Track Title",
      artist: "Test Artist",
      albumTitle: "Test Album Title",
      spotifyImageUrl: AVATAR_SRC,
      appleMusicImageUrl: AVATAR_SRC,
    },
  },
  {
    id: "28694a0f-3da1-451f-bd98-142456e29d72",
    active: true,
    fullName: "Aafreen Khan",
    author: {
      first: "Steve",
      last: "Jobs",
      username: "ettep",
    },
    track: {
      title: "Test Track Title",
      artist: "Test Artist",
      albumTitle: "Test Album Title",
      spotifyImageUrl: AVATAR_SRC,
      appleMusicImageUrl: AVATAR_SRC,
    },
  },
  {
    id: "28694a0f-3da1-451f-bd96-142456e69d72",
    active: true,
    fullName: "Aafreen Khan",
    author: {
      first: "Steve",
      last: "Jobs",
      username: "ettep",
    },
    track: {
      title: "Test Track Title",
      artist: "Test Artist",
      albumTitle: "Test Album Title",
      spotifyImageUrl: AVATAR_SRC,
      appleMusicImageUrl: AVATAR_SRC,
    },
  },
  {
    id: "28604a0f-3da1-451f-bd96-142456e29d72",
    active: true,
    fullName: "Aafreen Khan",
    author: {
      first: "Steve",
      last: "Jobs",
      username: "ettep",
    },
    track: {
      title: "Test Track Title",
      artist: "Test Artist",
      albumTitle: "Test Album Title",
      spotifyImageUrl: AVATAR_SRC,
      appleMusicImageUrl: AVATAR_SRC,
    },
  },
  {
    id: "21694a0f-3da1-451f-bd96-142456e29d72",
    active: true,
    fullName: "Aafreen Khan",
    author: {
      first: "Steve",
      last: "Jobs",
      username: "ettep",
    },
    track: {
      title: "Test Track Title",
      artist: "Test Artist",
      albumTitle: "Test Album Title",
      spotifyImageUrl: AVATAR_SRC,
      appleMusicImageUrl: AVATAR_SRC,
    },
  },
  {
    id: "28694a0f-3da1-451f-bd9l-142456e29d72",
    active: true,
    fullName: "Aafreen Khan",
    author: {
      first: "Steve",
      last: "Jobs",
      username: "ettep",
    },
    track: {
      title: "Test Track Title",
      artist: "Test Artist",
      albumTitle: "Test Album Title",
      spotifyImageUrl: AVATAR_SRC,
      appleMusicImageUrl: AVATAR_SRC,
    },
  },
];
